version: '3'

services:
  phpapp:
    image: phpapp:123
    ports:
      - "8080:80"
    volumes: 
      - "./:/var/www/html"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-php-app