version: '3'

services:
  phpapp:
    ports:
      - "80"
    build:
      context: ./
      dockerfile: Dockerfile
  phpapp2:
    ports:
      - "80"
    build:
      context: ./
      dockerfile: Dockerfile
